version: "2"
services:
  # Jaeger
  jaeger-all-in-one:
    # container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250"

  # OTEL Collector
  otel-collector:
    # container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel-collector/otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      # - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "13133:13133" # health_check extension
      - "1888:1888"   # pprof extension
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
  
  # Prometheus
  prometheus:
    # container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector